### PR TITLE
Ds 2836 2

### PR DESCRIPTION
**Pull request by jrwishart**

### CODE REVIEW

**Review by mwmclean — COMMENTED** [review]
What does the change in `test-dummyvariableadjustment.R` do?

**Comment by jrwishart** [comment]
Description was given in the commit message for that change in https://github.com/Displayr/flipRegression/pull/20/commits/ddd111387a072e1875287d8d61b81d70344ab07a. Essentially the tests there are based off randomly simulated data and sometimes the `Regression` output gives a warning about Unusual observations when doing the auxiliary checks, other times it gives no warning. The change there allows both the no warning and warning case to be caught and expected and avoids using suppressWarnings.

**Comment by mwmclean** [comment]
Why not set a seed or add as a data set in the `testthat/` directory and remove the randomization from the test?

**Comment by jrwishart** [comment]
I can set a seed. At the time of writing the code I felt a random input would more thoroughly test the functions over time. The other dummy variable tests are checking the dummy variables being created and that the regular slope coefficients don't change when the missing data is imputed back using the dummy slopes. Should I add a seed in to fix the input data?

**Pull request merged**
